AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyElasticBeanstalkApplication:
    Type: 'AWS::ElasticBeanstalk::Application'
    Properties:
      ApplicationName: my-app

  MyElasticBeanstalkEnvironment:
    Type: 'AWS::ElasticBeanstalk::Environment'
    Properties:
      EnvironmentName: my-app-env
      ApplicationName: !Ref MyElasticBeanstalkApplication
      SolutionStackName: 64bit Amazon Linux 2 v3.3.6 running Node.js 18
      OptionSettings:
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: NODE_ENV
          Value: production
        - Namespace: aws:elasticbeanstalk:container:nodejs
          OptionName: NodeCommand
          Value: npm start