AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyECRRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: my-app-repo

  MyECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: my-app-cluster

  MyECSTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: my-app-task
      ContainerDefinitions:
        - Name: my-app
          Image: !Sub 'AWS::AccountId.dkr.ecr.AWS::Region.amazonaws.com/my-app:latest'
          Memory: 512
          Cpu: 256
          Essential: true
          PortMappings:
            - ContainerPort: 5000
              HostPort: 5000

  MyECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref MyECSCluster
      TaskDefinition: !Ref MyECSTaskDefinition
      DesiredCount: 1