AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyAppBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: my-app-bucket

  MyAppBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyAppBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: elasticbeanstalk.amazonaws.com
            Action: s3:GetObject
            Resource: arn:aws:s3:::my-app-bucket/*
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::123456789012:role/MyAppAdminRole
            Action: s3:PutObject
            Resource: arn:aws:s3:::my-app-bucket/admin/*