AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: my-app-cpu-utilization
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref MySNSTopic
      Dimensions:
        - Name: ClusterName
          Value: my-app-cluster
        - Name: ServiceName
          Value: my-app-service