AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MySNSSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Protocol: email
      Endpoint: your-email@example.com
      TopicArn: !Ref MySNSTopic