AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: my-bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: elasticbeanstalk.amazonaws.com
            Action: s3:GetObject
            Resource: arn:aws:s3:::my-bucket/*