name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image to AWS ECR
        run: |
          docker tag my-app:latest { secrets.AWS_ECR_REGISTRY }/my-app:latest
          docker push { secrets.AWS_ECR_REGISTRY }/my-app:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-definition.json
          service: my-ecs-service
          cluster: my-ecs-cluster
          wait-for-service-stability: true