name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'cloudformation/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: { secrets.AWS_ACCESS_KEY_ID }
          aws-secret-access-key: { secrets.AWS_SECRET_ACCESS_KEY }
          aws-region: us-east-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy             --template-file cloudformation/infrastructure.yaml             --stack-name my-app-infrastructure             --capabilities CAPABILITY_NAMED_IAM