name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd client
          npm install
          cd ../server
          npm install

      - name: Run unit tests
        run: |
          cd client
          npm test -- --coverage
          cd ../server
          npm test -- --coverage

      - name: Run Cypress E2E tests
        run: |
          cd client
          npx cypress run